apiVersion: v1
kind: Service
metadata:
  name: repl-nodejs-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: repl-nodejs-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repl-nodejs-api
spec:
  selector:
    matchLabels:
      app: repl-nodejs-api
  replicas: 1
  template:
    metadata:
      labels:
        app: repl-nodejs-api
    spec:
      containers:
        - name: repl-nodejs-api
          image: mtrqq/repl-backend:0.1.0-nodejs
          env:
            - name: RLIMITER_BASE_URL
              value: http://rlimiter
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: repl-nodejs-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: repl-nodejs-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
