apiVersion: v1
kind: Service
metadata:
  name: rlimiter-redis-kv
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: rlimiter-redis-kv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlimiter-redis-kv
spec:
  selector:
    matchLabels:
      app: rlimiter-redis-kv
  replicas: 1
  template:
    metadata:
      labels:
        app: rlimiter-redis-kv
    spec:
      containers:
        - name: rlimiter-redis-kv
          image: redis:6.2.6
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: rlimiter
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: rlimiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlimiter
spec:
  selector:
    matchLabels:
      app: rlimiter
  replicas: 1
  template:
    metadata:
      labels:
        app: rlimiter
    spec:
      containers:
        - name: rlimiter
          image: mtrqq/repl-rlimiter:0.1.0
          env:
            - name: RLIMITER_REDIS_HOST
              value: rlimiter-redis-kv
            - name: RLIMITER_REDIS_PORT
              value: "6379"
            - name: RLIMITER_LIMIT
              value: "10"
            - name: RLIMITER_PERIOD
              value: minute
            - name: RLIMITER_PORT
              value: "80"
          ports:
            - containerPort: 80
